project:
  type: website
  output-dir: docs
website:
  title: "Ryan Hernandez"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
        # No 'file:' needed for index.qmd as it's typically 'index.html' by default
      - text: "HR Management"
        href: HR-Management.qmd
        file: HR-Management.html # Add this line
      - text: "Strategic Management"
        href: Strategic-Management.qmd
        file: Strategic-Management.html # Add this line
      - text: "Resume"
        href: Resume.qmd
        file: Resume.html # Add this line

format:
  html:
    theme: [flatly, theme.scss]
    toc: true