project:
  type: website
output-dir: docs 
website:
  title: "Ryan Hernandez"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "HR Management"
        href: HR-Management.html
      - text: "Strategic Management"
        href: Strategic-Management.html
      - text: "Resume"
        href: Resume.html

format:
  html:
    theme: [flatly, theme.scss]
    toc: true

